### ISSUE TITLE
Missing PyTorch in the requirements.txt?

### ISSUE THREAD

**Issue by samvelyan** [facebookresearch/torchbeast#1]
Hi there. Congratulations on the release. The platform looks great.

After following the installation guide for MonoBeast
```bash
$ conda create -n torchbeast python=3.7
$ conda activate torchbeast
$ pip install -r requirements.txt
```
and running 
```bash
python -m torchbeast.monobeast --env PongNoFrameskip-v4
```
I'm getting the following error `ModuleNotFoundError: No module named 'torch'`.

Looks like you're missing the torch prerequisite in the `requirements.txt` for the new `torchbeast` conda environment.

**Comment by heiner** [comment]
Hey Mikayel, thanks for the kind words!

You're absolutely right. We avoided adding PyTorch to `requirements.txt` in order to let users choose their preferred version, and because the installation for PolyBeast on Linux requires a special version of PyTorch due to binary incompatibilities. In https://github.com/facebookresearch/torchbeast/commit/7b5dd9a477fd7258ec7d582e08f3d8c04d2ac156 we added a PyTorch installation command to the installation guide.

Thanks for telling us and have fun using TorchBeast!
